# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170919_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
